language: node_js
node_js:
  - 10
before_install:
  - openssl aes-256-cbc -K $encrypted_08aa9827e538_key -iv $encrypted_08aa9827e538_iv
    -in deploy_rsa.enc -out ./deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - ssh-add ./deploy_rsa
script:
  - yarn
  - yarn build
addons:
  ssh_known_hosts: kulturspektakel.de
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ kultwiki@kulturspektakel.de:/var/www/virtual/kultwiki/booking.kulturspektakel.de
  on:
    branch: master
