language: node_js
node_js:
  - 10
addons:
  ssh_known_hosts: kultursp.uber.space
before_install:
  - openssl aes-256-cbc -K $encrypted_08aa9827e538_key -iv $encrypted_08aa9827e538_iv
    -in deploy_rsa.enc -out ./deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_rsa
  - ssh-add ./deploy_rsa
script:
  - yarn
  - yarn build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ kultursp@kultursp.uber.space:/var/www/virtual/kultursp/booking.kulturspektakel.de
  on:
    branch: master
