language: node_js
node_js:
  - 10
script:
  - yarn
  - yarn build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ kultwiki@kulturspektakel.de:/var/www/virtual/kultwiki/booking.kulturspektakel.de
  on:
    branch: master
